# vim: ft=tmux
# Catppuccin Mocha palette
set -g @ctp_bg "#1e1e2e"
set -g @ctp_fg "#cdd6f4"
set -g @ctp_mauve "#cba6f7"
set -g @ctp_blue "#89b4fa"
set -g @ctp_surface0 "#313244"
set -g @ctp_surface1 "#45475a"
set -g @ctp_surface2 "#585b70"
set -g @ctp_overlay0 "#6c7086"
set -g @ctp_green "#a6e3a1"
set -g @ctp_yellow "#f9e2af"

set -g mode-style "fg=#{@ctp_fg},bg=#{@ctp_surface1}"

set -g message-style "fg=#{@ctp_fg},bg=#{@ctp_surface1}"
set -g message-command-style "fg=#{@ctp_fg},bg=#{@ctp_surface1}"

set -g pane-border-style "fg=#{@ctp_surface0}"
set -g pane-active-border-style "fg=#{@ctp_mauve}"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#{@ctp_fg},bg=#{@ctp_bg}"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#{@ctp_bg},bg=#{@ctp_mauve},bold] #S #[fg=#{@ctp_mauve},bg=#{@ctp_surface1},nobold,nounderscore,noitalics]#[fg=#{@ctp_fg},bg=#{@ctp_surface1},bold] #(whoami) #[fg=#{@ctp_surface1},bg=#{@ctp_bg}]"
set -g status-right "#[fg=#{@ctp_surface1},bg=#{@ctp_bg},nobold,nounderscore,noitalics]#[fg=#{@ctp_fg},bg=#{@ctp_surface1},bold,nounderscore,noitalics] %d %b #[fg=#{@ctp_surface2},bg=#{@ctp_surface1}]#[fg=#{@ctp_surface2},bg=#{@ctp_surface1},nobold,nounderscore,noitalics]#[fg=#{@ctp_fg},bg=#{@ctp_surface2}]#[fg=#{@ctp_fg},bg=#{@ctp_surface2},bold,nounderscore,noitalics] %H:%M #[fg=#{@ctp_mauve},bg=#{@ctp_surface2}]#[fg=#{@ctp_bg},bg=#{@ctp_mauve},bold] #h "

setw -g window-status-activity-style "underscore,fg=#{@ctp_fg},bg=#{@ctp_bg}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#{@ctp_fg},bg=#{@ctp_bg}"
setw -g window-status-current-format '#[fg=#{@ctp_bg},bg=#{@ctp_blue}]#[fg=#{@ctp_bg},bg=#{@ctp_blue},bold] #I #[fg=#{@ctp_blue},bg=#{@ctp_yellow}] #[fg=#{@ctp_bg},bg=#{@ctp_yellow},bold]#W #[fg=#{@ctp_yellow},bg=#{@ctp_bg},nobold]'
# Inactive window style
# setw -g window-status-format '#[fg=#{@ctp_bg},bg=#{@ctp_surface1}]#[fg=#{@ctp_fg},bg=#{@ctp_surface1}] #I  #W #[fg=#{@ctp_surface1},bg=#{@ctp_bg}]'
# Inactive window (Dual-tone muted)
setw -g window-status-format '#[fg=#{@ctp_bg},bg=#{@ctp_overlay0}]#[fg=#{@ctp_bg},bg=#{@ctp_overlay0}] #I #[fg=#{@ctp_overlay0},bg=#{@ctp_surface1}]#[fg=#{@ctp_fg},bg=#{@ctp_surface1}] #W #[fg=#{@ctp_surface1},bg=#{@ctp_bg}]'

