[tools]
node = "lts"
python = "latest"

[settings]
# Automatically create virtualenv when a python version is specified in .mise.toml
python_venv_auto_create = true
# Shorthands for easy installs
# node = "lts"
# python = "3.12"
